import 'dart:io';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../pages/ui/pdf_preview_page.dart';
import '../../widgets/pdf/product_pdf_widget.dart';

Future<void> genPDF(BuildContext context, Map<String, dynamic> map) async {
  final pdf = pw.Document();
  final image = await _getImage(map['thumbnail']);

  // Monochrome PDF colors
  const accentColor = PdfColor.fromInt(0xFF000000); // Black
  const darkGrey = PdfColor.fromInt(0xFF212121);
  const lightGrey = PdfColor.fromInt(0xFF757575);
  const veryLightGrey = PdfColor.fromInt(0xFFF5F5F5);

  pdf.addPage(
    pw.MultiPage(
      pageTheme: pw.PageTheme(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        buildBackground: (context) => pw.FullPage(
          ignoreMargins: true,
          child: pw.Container(color: PdfColors.white),
        ),
      ),
      build: (pw.Context context) {
        return [
          // Header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'TAG TWEAKER',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                      color: accentColor,
                    ),
                  ),
                  pw.Text(
                    'PRODUCT CATALOG',
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: lightGrey,
                      letterSpacing: 2,
                    ),
                  ),
                ],
              ),
              pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decoration: pw.BoxDecoration(
                  color: accentColor,
                  borderRadius: pw.BorderRadius.circular(4),
                ),
                child: pw.Text(
                  'OFFICIAL DOCUMENT',
                  style: pw.TextStyle(
                    fontSize: 8,
                    color: PdfColors.white,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 10),
          pw.Divider(color: accentColor, thickness: 2),
          pw.SizedBox(height: 30),

          // Hero Section
          buildProductPdfWidget(
            map,
            image,
            accentColor,
            darkGrey,
            lightGrey,
            veryLightGrey,
          ),

          pw.Spacer(),

          // Footer
          pw.Divider(color: lightGrey, thickness: 0.5),
          pw.SizedBox(height: 10),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Generated by Tag Tweaker',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: lightGrey,
                ),
              ),
              pw.Text(
                'Page 1',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: lightGrey,
                ),
              ),
            ],
          ),
        ];
      },
    ),
  );

  final output = await getTemporaryDirectory();
  final file = File('${output.path}/${map['title']}_catalog.pdf');
  await file.writeAsBytes(await pdf.save());
  try {
    if (context.mounted) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => PdfPreviewScreen(pdfPath: file.path),
        ),
      );
    }
  } catch (e) {
    debugPrint('Error navigating to PDF preview screen: $e');
  }
}

Future<pw.MemoryImage?> _getImage(String url) async {
  try {
    final response = await http.get(Uri.parse(url));
    if (response.statusCode == 200) {
      return pw.MemoryImage(response.bodyBytes);
    } else {
      debugPrint(
          'Image failed with status ${response.statusCode}, using placeholder');
      return await _getPlaceholderImage();
    }
  } catch (e) {
    debugPrint('Error loading image from URL: $e, using placeholder');
    return await _getPlaceholderImage();
  }
}

Future<pw.MemoryImage?> _getPlaceholderImage() async {
  try {
    final placeholderUrl =
        'https://via.placeholder.com/400x400/4FD8C4/ffffff?text=Product+Image';
    final response = await http.get(Uri.parse(placeholderUrl));
    if (response.statusCode == 200) {
      return pw.MemoryImage(response.bodyBytes);
    }
  } catch (e) {
    debugPrint('Error loading placeholder image: $e');
  }
  return null;
}
