// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAikjFp-pCDZ-fKkNvZO1cFSra2reYQIJs',
    appId: '1:768847026435:android:12d5205e1198d3e5167136',
    messagingSenderId: '768847026435',
    projectId: 'tagtweaker-sheersh',
    storageBucket: 'tagtweaker-sheersh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAubx4fZ9J-ISAEEvEoCote6R0v0Re1RvY',
    appId: '1:768847026435:ios:b79072a4f2db9b96167136',
    messagingSenderId: '768847026435',
    projectId: 'tagtweaker-sheersh',
    storageBucket: 'tagtweaker-sheersh.appspot.com',
    androidClientId: '768847026435-0cilj3eqem6l0h1icf1oqkg839e9dupn.apps.googleusercontent.com',
    iosClientId: '768847026435-vqpcarcltvegdrqsehonm9ssjormr731.apps.googleusercontent.com',
    iosBundleId: 'com.example.catalogueApp',
  );
}
